[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Modules
logging = { path = "../logging", optional = true }

# Other




[features]
logging = ["dep:logging"]