[package]
name = "fulmen"
description = "ECS based Vulkan Game Engine made with Rust."
version = "0.0.1"
edition = "2021"

authors = ["Xeros08 <42175313+Xeros08@users.noreply.github.com>"]


[workspace]
resolver = "2"
members = ["modules/*"]


[workspace.dependencies]
# Logging
thiserror = { version = ">=1.0.60" }
log = { version = ">=0.4" }

[dependencies]
# Engine Modules
fulmen_core = { path = "modules/fulmen_core" }
fulmen_ecs = { path = "modules/fulmen_ecs" }

[features]
default = ["rendering"]

rendering = ["fulmen_core/rendering"]
logging = ["fulmen_core/logging"]
debug_logging = ["fulmen_core/debug_logging"]
