[package]
name = "fulmen_ptr"
description = "Fulmen's internal raw pointer types."
version = "0.1.0"
crate-type = ["lib"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Modules

# Logging
thiserror = { workspace = true }

# Other

[features]
default = []